version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pr_postgres
    restart: always
    environment:
      POSTGRES_DB: pullreview
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pullreview"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: pr_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: pullreview
    ports:
      - "8080:8080"
    command: ["./entrypoint.sh"]

volumes:
  postgres_data:
